import { Routes } from '@angular/router';

export const DODS_PLAYGROUND_ROUTES: Routes = [
  {
    path: '',
    loadComponent: () =>
      import('./shell/playground-shell.component').then(m => m.DodsPlaygroundShellComponent),
    children: [
      { path: '', pathMatch: 'full',
        loadComponent: () => import('./stories/overview.story').then(m => m.DodsOverviewStoryComponent) },
      { path: 'tokens',
        loadComponent: () => import('./stories/tokens.story').then(m => m.DodsTokensStoryComponent) },
      { path: 'button',
        loadComponent: () => import('./stories/button.story').then(m => m.DodsButtonStoryComponent) },
      { path: 'card',
        loadComponent: () => import('./stories/card.story').then(m => m.DodsCardStoryComponent) },
      { path: 'divider',
        loadComponent: () => import('./stories/divider.story').then(m => m.DodsDividerStoryComponent) },
      { path: 'input',
        loadComponent: () => import('./stories/input.story').then(m => m.DodsInputStoryComponent) },
      { path: 'textarea',
        loadComponent: () => import('./stories/textarea.story').then(m => m.DodsTextareaStoryComponent) },
      { path: 'select',
        loadComponent: () => import('./stories/select.story').then(m => m.DodsSelectStoryComponent) },
      { path: 'checkbox',
        loadComponent: () => import('./stories/checkbox.story').then(m => m.DodsCheckboxStoryComponent) },
      { path: 'radio',
        loadComponent: () => import('./stories/radio.story').then(m => m.DodsRadioStoryComponent) },
      { path: 'switch',
        loadComponent: () => import('./stories/switch.story').then(m => m.DodsSwitchStoryComponent) },
      { path: 'badge',
        loadComponent: () => import('./stories/badge.story').then(m => m.DodsBadgeStoryComponent) },
      { path: 'chip',
        loadComponent: () => import('./stories/chip.story').then(m => m.DodsChipStoryComponent) },
      { path: 'avatar',
        loadComponent: () => import('./stories/avatar.story').then(m => m.DodsAvatarStoryComponent) },
      { path: 'tabs',
        loadComponent: () => import('./stories/tabs.story').then(m => m.DodsTabsStoryComponent) },
      { path: 'modal',
        loadComponent: () => import('./stories/modal.story').then(m => m.DodsModalStoryComponent) },
      { path: 'toast',
        loadComponent: () => import('./stories/toast.story').then(m => m.DodsToastStoryComponent) },
      { path: 'tooltip',
        loadComponent: () => import('./stories/tooltip.story').then(m => m.DodsTooltipStoryComponent) },
      { path: 'spinner',
        loadComponent: () => import('./stories/spinner.story').then(m => m.DodsSpinnerStoryComponent) },
      { path: 'progress-bar',
        loadComponent: () => import('./stories/progress-bar.story').then(m => m.DodsProgressBarStoryComponent) },
    ],
  },
];
