#!/usr/bin/env node
// Generates client/src/app/styles/_tokens.scss from design-tokens/tokens.json.
// Run:  npm run tokens            (writes _tokens.scss)
//       npm run tokens -- --check (fails if out of sync; for CI)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CLIENT_ROOT = join(__dirname, '..');
const SRC = join(CLIENT_ROOT, 'src', 'design-tokens', 'tokens.json');
const OUT_DIR = join(CLIENT_ROOT, 'src', 'app', 'styles');
const OUT = join(OUT_DIR, '_tokens.scss');

const isCheck = process.argv.includes('--check');
const tokens = JSON.parse(readFileSync(SRC, 'utf8'));

function resolveRef(value) {
  if (typeof value !== 'string' || !value.startsWith('{') || !value.endsWith('}')) return value;
  const path = value.slice(1, -1).split('.');
  let node = tokens;
  for (const seg of path) {
    if (node == null) break;
    node = node[seg];
  }
  if (node && typeof node === 'object' && '$value' in node) return resolveRef(node.$value);
  return node;
}

function flatten(obj, prefix = [], out = []) {
  for (const [key, val] of Object.entries(obj)) {
    if (key.startsWith('$')) continue;
    if (val && typeof val === 'object' && '$value' in val) {
      out.push({ path: [...prefix, key], value: resolveRef(val.$value), type: val.$type });
    } else if (val && typeof val === 'object') {
      flatten(val, [...prefix, key], out);
    }
  }
  return out;
}

function toVarName(path) {
  const p = [...path];
  if (p[0] === 'primitive') p.shift();
  else if (p[0] === 'semantic') p.splice(0, 2);
  return '--do-' + p.join('-').toLowerCase();
}

const flat = flatten(tokens);
const primitives = flat.filter(t => t.path[0] === 'primitive');
const lightSem   = flat.filter(t => t.path[0] === 'semantic' && t.path[1] === 'light');
const darkSem    = flat.filter(t => t.path[0] === 'semantic' && t.path[1] === 'dark');

const lines = [];
lines.push('// AUTO-GENERATED by client/scripts/build-tokens.mjs — do not edit.');
lines.push('// Regenerate with: npm run tokens (from client/).');
lines.push('');
lines.push(':root {');
lines.push('  // primitives (shared across themes)');
for (const t of primitives) lines.push(`  ${toVarName(t.path)}: ${t.value};`);
lines.push('');
lines.push('  // semantic (light — default)');
for (const t of lightSem) lines.push(`  ${toVarName(t.path)}: ${t.value};`);
lines.push('}');
lines.push('');
lines.push('[data-theme="dark"] {');
lines.push('  // semantic (dark)');
for (const t of darkSem) lines.push(`  ${toVarName(t.path)}: ${t.value};`);
lines.push('}');
lines.push('');

const output = lines.join('\n');

if (isCheck) {
  try {
    const current = readFileSync(OUT, 'utf8');
    if (current !== output) {
      console.error('✖ _tokens.scss is out of sync with tokens.json. Run `npm run tokens`.');
      process.exit(1);
    }
    console.log('✔ _tokens.scss matches tokens.json (' + flat.length + ' tokens)');
  } catch (e) {
    if (e.code === 'ENOENT') {
      console.error('✖ _tokens.scss does not exist. Run `npm run tokens`.');
      process.exit(1);
    }
    throw e;
  }
} else {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, output);
  console.log(`✔ Wrote ${flat.length} tokens to ${OUT}`);
}
