import { jsPDF } from "jspdf";
import type { Invoice, InvoiceItem, Patient, Clinic } from "@/types";

interface InvoicePdfData {
  invoice: Invoice;
  items: InvoiceItem[];
  patient: Patient;
  clinic: Clinic;
}

export function generateInvoicePdf(data: InvoicePdfData): jsPDF {
  const { invoice, items, patient, clinic } = data;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 16;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ── Header ──
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(clinic.name, margin, y);

  doc.setFontSize(14);
  doc.setTextColor(0, 128, 128);
  doc.text("INVOICE", pageWidth - margin, y, { align: "right" });
  doc.setTextColor(0);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  doc.text(`${clinic.address}, ${clinic.city} - ${clinic.pincode}`, margin, y);
  doc.text(`#${invoice.invoice_number}`, pageWidth - margin, y, { align: "right" });
  y += 4;
  doc.text(`Phone: ${clinic.phone} | Email: ${clinic.email}`, margin, y);
  doc.text(`Date: ${new Date(invoice.created_at).toLocaleDateString("en-IN")}`, pageWidth - margin, y, { align: "right" });
  if (clinic.gstin) {
    y += 4;
    doc.text(`GSTIN: ${clinic.gstin}`, margin, y);
  }
  y += 3;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // ── Bill To ──
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(margin, y - 4, contentWidth, 20, 2, 2, "F");

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(60);
  doc.text("Bill To:", margin + 4, y + 1);

  doc.setFont("helvetica", "normal");
  doc.text(patient.full_name, margin + 22, y + 1);
  doc.text(`Phone: ${patient.phone}`, margin + 4, y + 6);
  doc.text(`ID: ${patient.patient_uid}`, margin + 4, y + 11);
  if (patient.address) {
    doc.text(patient.address, contentWidth / 2 + margin, y + 6);
  }

  y += 24;

  // ── Items Table ──
  doc.setFillColor(0, 128, 128);
  doc.roundedRect(margin, y, contentWidth, 7, 1, 1, "F");

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255);
  const cols = [margin + 3, margin + 8, margin + 100, margin + 125, margin + 155];
  doc.text("#", cols[0], y + 5);
  doc.text("Description", cols[1], y + 5);
  doc.text("Qty", cols[2], y + 5);
  doc.text("Unit Price", cols[3], y + 5);
  doc.text("Amount", cols[4], y + 5);
  y += 10;

  doc.setTextColor(40);
  doc.setFont("helvetica", "normal");

  const fmt = (n: number) =>
    new Intl.NumberFormat("en-IN", {
      style: "currency",
      currency: "INR",
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
    }).format(n);

  items.forEach((item, i) => {
    if (i % 2 === 0) {
      doc.setFillColor(250, 251, 252);
      doc.rect(margin, y - 4, contentWidth, 8, "F");
    }
    doc.setFontSize(8);
    doc.text(String(i + 1), cols[0], y);
    doc.text(item.description, cols[1], y);
    doc.text(String(item.quantity), cols[2], y);
    doc.text(fmt(item.unit_price), cols[3], y);
    doc.text(fmt(item.amount), cols[4], y);
    y += 8;
  });

  y += 4;

  // ── Totals ──
  const totalsX = pageWidth - margin - 70;
  doc.setDrawColor(220);
  doc.line(totalsX, y, pageWidth - margin, y);
  y += 6;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text("Subtotal:", totalsX, y);
  doc.text(fmt(invoice.subtotal), pageWidth - margin, y, { align: "right" });
  y += 5;

  doc.text(`GST (${invoice.gst_percent}%):`, totalsX, y);
  doc.text(fmt(invoice.gst_amount), pageWidth - margin, y, { align: "right" });
  y += 5;

  if (invoice.discount > 0) {
    doc.text("Discount:", totalsX, y);
    doc.text(`-${fmt(invoice.discount)}`, pageWidth - margin, y, { align: "right" });
    y += 5;
  }

  doc.setDrawColor(0, 128, 128);
  doc.line(totalsX, y, pageWidth - margin, y);
  y += 6;

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 128, 128);
  doc.text("Total:", totalsX, y);
  doc.text(fmt(invoice.total), pageWidth - margin, y, { align: "right" });
  y += 8;

  // Payment info
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80);
  doc.text(`Payment Mode: ${invoice.payment_mode.toUpperCase()}`, totalsX, y);
  y += 4;

  const statusColor = invoice.payment_status === "paid" ? [16, 185, 129] : [245, 158, 11];
  doc.setTextColor(statusColor[0], statusColor[1], statusColor[2]);
  doc.setFont("helvetica", "bold");
  doc.text(`Status: ${invoice.payment_status.toUpperCase()}`, totalsX, y);

  // ── Footer ──
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setDrawColor(200);
  doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(150);
  doc.text("This is a computer-generated invoice.", margin, footerY);
  doc.text(`Generated by Doctors Office — ${clinic.name}`, pageWidth - margin, footerY, { align: "right" });

  return doc;
}

export function downloadInvoicePdf(data: InvoicePdfData) {
  const doc = generateInvoicePdf(data);
  doc.save(`Invoice-${data.invoice.invoice_number}-${Date.now()}.pdf`);
}

export function getInvoicePdfBlob(data: InvoicePdfData): Blob {
  const doc = generateInvoicePdf(data);
  return doc.output("blob");
}
